### ISSUE TITLE
summaryFilterItems in CustomField is generated as a required field

### ISSUE THREAD

**Issue by akedalat** [jsforce/jsforce#1572] opened 2024-09-05 13:13 UTC
[summaryFilterItems](https://github.com/jsforce/jsforce/blob/506754881681be31daa891d09e8daaa741ceec59/src/api/metadata/schema.ts#L10879) in the CustomField type is supposed to be an optional field but it gets generated as required despite [having minOccurs set to 0](https://github.com/jsforce/jsforce/blob/506754881681be31daa891d09e8daaa741ceec59/src/api/metadata/wsdl.xml#L3101).

**Comment by cristiand391** [comment] 2024-09-05 14:55
I think it's because the `summaryFilterItems` is expected to be an array of FilterItems:
> 
summaryFilterItems | FilterItem[] | Represents the set of filter conditions for this field if it's a summary field. This field is summed on the child if the filter conditions are met.
-- | -- | --

https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/customfield.htm

the type generator will not make it nullable if it's an array (I assume b/c you can pass an empty array for that, but can't confirm since it's been written a few years ago).

fwiw, we created a new TS types package that's up-to-date with Salesforce releases:
https://github.com/jsforce/jsforce/discussions/1530

I've looked and it matches the same behavior `summaryFilterItems: FilterItem[];`

**Comment by cristiand391** [comment] 2024-09-25 21:08
closing as I think it's working as designed. Feel free to re-open if needed.

**Closed by cristiand391** 2024-09-25 21:08 UTC
Labels: more info needed
