### ISSUE TITLE
passwordExpired is not handled

### ISSUE THREAD

**Issue by thib3113** [jsforce/jsforce#1308] opened 2023-02-20 15:51 UTC
Hello,

I didn't see an issue about this, so I create one . 

when doing 
```js
const sfconn = new jsforce.Connection({
    loginUrl: 'https://test.salesforce.com'
  })
await sfconn.login(
  username,
  password`
)
```

It will do a soap call to salesforce, and fail only if status >= 400 . 

My problem was in my case salesforce return 200 with : 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns="urn:partner.soap.sforce.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Body>
        <loginResponse>
            <result>
                [...]
                <passwordExpired>true</passwordExpired>
                [...]
            </result>
        </loginResponse>
    </soapenv:Body>
</soapenv:Envelope>
```

and this will success . 

So, if I want to do a query, this will loop trying to do a request, and salesforce telling
```json
[{"message":"Your password has expired. Please reset your password.","errorCode":"INVALID_OPERATION_WITH_EXPIRED_PASSWORD"}]
```

So, I see two problems : 
 - query loop never end (so retrying each times to call salesforce)
 - passwordExpired is not handled on login
 
 
 PS : I know you're working on the V2, and I'm not blocked by this problem, it's just FYI

**Comment by matthewhenry1** [comment] 2023-06-07 22:13
I've just run into this issue, it's a silent killer.

As shared above, the crux of the issue is that the code base doesn't recognize `passwordExpired` as a response object. Despite being present in the [loginResult](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_login_loginresult.htm).

Since the `login()` method returns a 200, it seems as if the user has authenticated. However until you execute a method like `describe()` with the connection object you'll find that the code base will continuously loop attempting to re-execute the `login()` method despite the password being expired. This will result in a login rate limit being exceeded or worse the account being locked out.

Tediously, the only way to determine if the account has a valid password is to initialize the connection object with the `instanceUrl` and `accessToken` then execute a method like `identity()` to actually verify if the password is valid, only then will you receive: `INVALID_OPERATION_WITH_EXPIRED_PASSWORD: Your password has expired. Please reset your password.`

`
const jsforce = require("jsforce");
const username = "myusername";
const password = "mypassword";
const loginUrl = "https://login.salesforce.com";
const logLevel = "DEBUG";

(async () => {

	// This will login fine, nothing about passwordExpired
	const conn = new jsforce.Connection({ loginUrl, logLevel });
	const initialLogin = await conn.login(username, password);
	console.log(`initialLogin ${JSON.stringify(initialLogin)}`); // this response will succeed

	// This will succeed as well...
	const identity = await conn.identity();
	console.log(`identity: ${JSON.stringify(identity)}`);

	// If you uncomment this it will go into a continuous loop until the user account hits a rate limit for logins or worse is locked out
	// const opportunityDescribe = await conn.describe("Opportunity");
	// console.log(`opportunityDescribe: ${JSON.stringify(opportunityDescribe)}`);

	// Only this will fail with: INVALID_OPERATION_WITH_EXPIRED_PASSWORD: Your password has expired. Please reset your password.
	const newConn = new jsforce.Connection({ instanceUrl: conn.instanceUrl, accessToken: conn.accessToken, logLevel });
	const newIdentity = await newConn.identity();
	console.log(`newIdentity: ${JSON.stringify(newIdentity)}`);
})();
`

**Comment by matthewhenry1** [comment] 2023-06-07 22:14
I've just run into this issue, it's a silent killer.

As shared above, the crux of the issue is that the code base doesn't recognize `passwordExpired` as a response object. Despite being present in the [loginResult](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_login_loginresult.htm).

Since the `login()` method returns a 200, it seems as if the user has authenticated. However until you execute a method like `describe()` with the connection object you'll find that the code base will continuously loop attempting to re-execute the `login()` method despite the password being expired. This will result in a login rate limit being exceeded or worse the account being locked out.

Tediously, the only way to determine if the account has a valid password is to initialize the connection object with the `instanceUrl` and `accessToken` then execute a method like `identity()` to actually verify if the password is valid, only then will you receive: `INVALID_OPERATION_WITH_EXPIRED_PASSWORD: Your password has expired. Please reset your password.`

```
const jsforce = require("jsforce");
const username = "myusername";
const password = "mypassword";
const loginUrl = "https://login.salesforce.com";
const logLevel = "DEBUG";

(async () => {

	// This will login fine, nothing about passwordExpired
	const conn = new jsforce.Connection({ loginUrl, logLevel });
	const initialLogin = await conn.login(username, password);
	console.log(`initialLogin ${JSON.stringify(initialLogin)}`); // this response will succeed

	// This will succeed as well...
	const identity = await conn.identity();
	console.log(`identity: ${JSON.stringify(identity)}`);

	// If you uncomment this it will go into a continuous loop until the user account hits a rate limit for logins or worse is locked out
	// const opportunityDescribe = await conn.describe("Opportunity");
	// console.log(`opportunityDescribe: ${JSON.stringify(opportunityDescribe)}`);

	// Only this will fail with: INVALID_OPERATION_WITH_EXPIRED_PASSWORD: Your password has expired. Please reset your password.
	const newConn = new jsforce.Connection({ instanceUrl: conn.instanceUrl, accessToken: conn.accessToken, logLevel });
	const newIdentity = await newConn.identity();
	console.log(`newIdentity: ${JSON.stringify(newIdentity)}`);
})();
```

**Comment by matthewhenry1** [comment] 2023-06-07 22:46
I've just run into this issue, it's a silent killer.

As shared above, the crux of the issue is that the code base doesn't recognize `passwordExpired` as a response object. Despite being present in the [loginResult](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_login_loginresult.htm).

Since the `login()` method returns a 200, it seems as if the user has authenticated. However until you execute a method like `describe()` with the connection object, you'll find that the code base will continuously loop attempting to re-execute the `login()` given it's returning a 401, despite the password being expired. This will result in a login rate limit being exceeded or worse the account being locked out. Worse, if you don't have `logLevel` set to `DEBUG` you'll have no idea why the transaction is taking so long 😅 

Tediously, the only way to determine if the account has a valid password is to initialize the connection object with the `instanceUrl` and `accessToken` then execute a method like `identity()` to actually verify if the password is valid, only then will you receive: `INVALID_OPERATION_WITH_EXPIRED_PASSWORD: Your password has expired. Please reset your password.`

Execute the code below with an account that has an expired password to replicate the issue.

```javascript
const jsforce = require("jsforce");
const username = "myusername";
const password = "mypassword";
const loginUrl = "https://login.salesforce.com";
const logLevel = "DEBUG";

(async () => {

	// This will login fine, nothing about passwordExpired
	const conn = new jsforce.Connection({ loginUrl, logLevel });
	const initialLogin = await conn.login(username, password);
	console.log(`initialLogin ${JSON.stringify(initialLogin)}`); // this response will succeed

	// This will succeed as well...
	const identity = await conn.identity();
	console.log(`identity: ${JSON.stringify(identity)}`);

	// If you uncomment this it will go into a continuous loop until the user account hits a rate limit for logins or worse is locked out
	// const opportunityDescribe = await conn.describe("Opportunity");
	// console.log(`opportunityDescribe: ${JSON.stringify(opportunityDescribe)}`);

	// Only this will fail with: INVALID_OPERATION_WITH_EXPIRED_PASSWORD: Your password has expired. Please reset your password.
	const newConn = new jsforce.Connection({ instanceUrl: conn.instanceUrl, accessToken: conn.accessToken, logLevel });
	const newIdentity = await newConn.identity();
	console.log(`newIdentity: ${JSON.stringify(newIdentity)}`);
})();
```

FWIW, with `logLevel` set to `DEBUG` you will see `passwordExpired`  on the first, _seemingly_ successful,`conn.login(username, password)`
```XML
<passwordExpired>true</passwordExpired
```
however, it took quite some debugging to realize find this.

So what does this all mean? You **always** have to ensure the connection object is "healthy" by executing `new jsforce.Connection({ instanceUrl: conn.instanceUrl, accessToken: conn.accessToken })` and then running a method like `identity()`

**Comment by matthewhenry1** [comment] 2023-07-13 17:41
```
javascript
const jsforce = require("jsforce");
const config = require("../configs");
const { logger } = require("../configs/logger");

const getAuthorizationPassword = () => {
	let authorizationPassword;
	if (config.SALESFORCE.SECURITY_TOKEN && config.SALESFORCE.SECURITY_TOKEN !== "") {
		authorizationPassword = `${config.SALESFORCE.PASSWORD}${config.SALESFORCE.SECURITY_TOKEN}`;
	} else {
		authorizationPassword = config.SALESFORCE.PASSWORD;
	}
	return authorizationPassword;
};

const login = async () => {
	const conn = new jsforce.Connection({
		logLevel: config.SALESFORCE.LOGLEVEL,
		loginUrl: config.SALESFORCE.LOGINURL,
		version: config.SALESFORCE.VERSION,
	});

	await conn.login(config.SALESFORCE.USERNAME, getAuthorizationPassword());
	const { accessToken, instanceUrl } = conn;
	return { accessToken, instanceUrl };
};

const refreshFn = async (conn, callback) => {
	try {
		logger.debug(`Salesforce connection.refreshFn establishing new connection`);

		// this solves for instances with the accessToken has expired and needs to simply be refreshed via another login
		conn.loginUrl = config.SALESFORCE.LOGINURL;
		await conn.login(config.SALESFORCE.USERNAME, getAuthorizationPassword());
		await conn.identity();

		// this new connection checks if the password is expired, see https://github.com/jsforce/jsforce/issues/1308#issuecomment-1581617384
		const { accessToken, instanceUrl } = conn;
		const newConn = new jsforce.Connection({ instanceUrl, accessToken, logLevel: config.SALESFORCE.LOGLEVEL });
		await newConn.identity();

		callback(null, accessToken);
	} catch (e) {
		logger.error(`Salesforce refreshFn error ${e}`);
		return callback(e);
	}
};

const connection = new jsforce.Connection({
	refreshFn,
	version: config.SALESFORCE.VERSION,
	logLevel: config.SALESFORCE.LOGLEVEL,
});

(async () => {
	const { accessToken, instanceUrl } = await login();

	// setting the connection with the instanceUrl and accessToken is the only way to get the refreshFn called
	connection.accessToken = accessToken;
	connection.instanceUrl = instanceUrl;
	await connection.identity();
})();

module.exports = { connection };
```

**Comment by matthewhenry1** [comment] 2023-07-13 17:44
Solution as an exported module

```javascript
const jsforce = require("jsforce");
const config = {
	SALESFORCE: {
		USERNAME: "myusername",
		PASSWORD: "mypassword",
		LOGINURL: "https://login.salesforce.com",
		LOGLEVEL: "DEBUG",
		VERSION: "57.0"
	}
};

const getAuthorizationPassword = () => {
	let authorizationPassword;
	if (config.SALESFORCE.SECURITY_TOKEN && config.SALESFORCE.SECURITY_TOKEN !== "") {
		authorizationPassword = `${config.SALESFORCE.PASSWORD}${config.SALESFORCE.SECURITY_TOKEN}`;
	} else {
		authorizationPassword = config.SALESFORCE.PASSWORD;
	}
	return authorizationPassword;
};

const login = async () => {
	const conn = new jsforce.Connection({
		logLevel: config.SALESFORCE.LOGLEVEL,
		loginUrl: config.SALESFORCE.LOGINURL,
		version: config.SALESFORCE.VERSION,
	});

	await conn.login(config.SALESFORCE.USERNAME, getAuthorizationPassword());
	const { accessToken, instanceUrl } = conn;
	return { accessToken, instanceUrl };
};

const refreshFn = async (conn, callback) => {
	try {
		console.debug(`Salesforce connection.refreshFn establishing new connection`);

		// this solves for instances with the accessToken has expired and needs to simply be refreshed via another login
		conn.loginUrl = config.SALESFORCE.LOGINURL;
		await conn.login(config.SALESFORCE.USERNAME, getAuthorizationPassword());
		await conn.identity();

		// this new connection checks if the password is expired, see https://github.com/jsforce/jsforce/issues/1308#issuecomment-1581617384
		const { accessToken, instanceUrl } = conn;
		const newConn = new jsforce.Connection({ instanceUrl, accessToken, logLevel: config.SALESFORCE.LOGLEVEL });
		await newConn.identity();

		callback(null, accessToken);
	} catch (e) {
		console.error(`Salesforce refreshFn error ${e}`);
		return callback(e);
	}
};

const connection = new jsforce.Connection({
	refreshFn,
	version: config.SALESFORCE.VERSION,
	logLevel: config.SALESFORCE.LOGLEVEL,
});

(async () => {
	const { accessToken, instanceUrl } = await login();

	// setting the connection with the instanceUrl and accessToken is the only way to get the refreshFn called
	connection.accessToken = accessToken;
	connection.instanceUrl = instanceUrl;
	await connection.identity();
})();

module.exports = { connection };
```

**Comment by cristiand391** [comment] 2024-07-15 19:09
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529

**Closed by cristiand391** 2024-07-15 19:09 UTC
Labels: bug, fixed in v3
